### ISSUE TITLE
Slyum do not launch on macOS aarch64 using Temurin-17

### ISSUE THREAD

**Issue by porchy13** [HEIG-GAPS/slyum#120]
Temurin-17 seems to have dropped the EAWT support on macOS. Below, the log at startup.

```
Full screen mode is not supported
Mac OS X Adapter could not talk to EAWT:
Mac OS X Adapter could not talk to EAWT:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "com.apple.java.OSXAdapter.macOSXApplication" is null
	at com.apple.java.OSXAdapter.setAboutHandler(OSXAdapter.java:79)
	at swing.Slyum.handleMacOSX(Slyum.java:1600)
	at swing.Slyum.<init>(Slyum.java:719)
	at swing.Slyum.main(Slyum.java:634)
```

It's maybe the time to switch to JavaFX !!

**Comment by porchy13** [comment]
Fixed in the new version: https://github.com/HEIG-GAPS/slyum/releases/tag/slyum-5.1.0
